version: '2'
services:
  zabbix-server:
    image: netw0rm/zabbix:3.0-xxl
    container_name: zabbix-server
    depends_on:
      - zabbix-db
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - zabbix-alertscripts:/usr/local/share/zabbix/alertscripts
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=mypass
      - XXL_zapix=true
      - XXL_grapher=true
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    container_name: zabbix_db
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=mypass
volumes:
  zabbix-alertscripts:
    driver: local
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
