serve:
  image: netw0rm/zabbix:2.4
  container_name: zabbix-server
  ports:
    - "80:80"
    - "10051:10051"
  volumes:
    - zab_alscripts:/usr/local/share/zabbix/alertscripts
    #- zab_exscripts:/usr/local/share/zabbix/externalscripts
  environment:
    ZS_DBHost: db
    ZS_DBUser: admin
    ZS_DBPassword: mypass
  links:
    - db
  restart: always
db:
  image: zabbix/zabbix-db-mariadb
  container_name: zabbix-db
  volumes:
    - zab_db_backups:/backups
    - zab_db:/var/lib/mysql
  environment:
    MARIADB_USER: admin
    MARIADB_PASS: mypass
  restart: always
